CREATE DATABASE T_SSolve

USE T_SSolve

CREATE TABLE Clientes
(
	IdCliente		INT PRIMARY KEY IDENTITY NOT NULL 
	,NomeFatasia	VARCHAR(255) NOT NULL
	,CNPJ			VARCHAR(14) NOT NULL UNIQUE
	,RazaoSocial	VARCHAR(255) NOT NULL UNIQUE
	,Endereço		VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE Clientes 
	ALTER COLUMN CNPJ VARCHAR(255);

CREATE TABLE Trabalhos
(
	IdTrabalho		INT PRIMARY KEY IDENTITY NOT NULL
	,Nome			VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Comodos
(
	IdComodo		INT PRIMARY KEY IDENTITY NOT NULL
	,Nome			VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Funcionarios
(
	IdFuncionario	INT PRIMARY KEY IDENTITY NOT NULL
	,Nome			VARCHAR(255) NOT NULL
);

CREATE TABLE Servicos
(
	IdServico		INT PRIMARY KEY IDENTITY NOT NULL
	,IdCliente		INT FOREIGN KEY REFERENCES Clientes (IdCliente)
	,IdTrabalho		INT FOREIGN KEY REFERENCES Trabalhos (IdTrabalho)
	,Descricao		VARCHAR(255) NOT NULL
	,IdComodo		INT FOREIGN KEY REFERENCES Comodos (IdComodo)
	,Duracao		DATETIME NOT NULL
	,Preco			VARCHAR(255) NOT NULL 
	,Localizacao	VARCHAR(255) NOT NULL 
);

CREATE TABLE Servico_Funcionario
(
	IdServico		INT FOREIGN KEY REFERENCES Servicos (IdServico)
	,IdFuncionario  INT FOREIGN KEY REFERENCES Funcionarios (IdFuncionario)
);